#ifndef SYSCALLID_H
#define SYSCALLID_H

#include <cstdint>
#include <string>
#include <unordered_map>

// Linux x86_64 system call numbers
enum UnixSyscall : uint16_t {
  kSysRead = 0,
  kSysWrite = 1,
  kSysOpen = 2,
  kSysClose = 3,
  kSysStat = 4,
  kSysFstat = 5,
  kSysLstat = 6,
  kSysPoll = 7,
  kSysLseek = 8,
  kSysMmap = 9,
  kSysMprotect = 10,
  kSysMunmap = 11,
  kSysBrk = 12,
  kSysRtSigaction = 13,
  kSysRtSigprocmask = 14,
  kSysRtSigreturn = 15,
  kSysIoctl = 16,
  kSysPread64 = 17,
  kSysPwrite64 = 18,
  kSysReadv = 19,
  kSysWritev = 20,
  kSysAccess = 21,
  kSysPipe = 22,
  kSysSelect = 23,
  kSysSchedYield = 24,
  kSysMremap = 25,
  kSysMsync = 26,
  kSysMincore = 27,
  kSysMadvise = 28,
  kSysShmget = 29,
  kSysShmat = 30,
  kSysShmctl = 31,
  kSysDup = 32,
  kSysDup2 = 33,
  kSysPause = 34,
  kSysNanosleep = 35,
  kSysGetitimer = 36,
  kSysAlarm = 37,
  kSysSetitimer = 38,
  kSysGetpid = 39,
  kSysSendfile = 40,
  kSysSocket = 41,
  kSysConnect = 42,
  kSysAccept = 43,
  kSysSendto = 44,
  kSysRecvfrom = 45,
  kSysSendmsg = 46,
  kSysRecvmsg = 47,
  kSysShutdown = 48,
  kSysBind = 49,
  kSysListen = 50,
  kSysGetsockname = 51,
  kSysGetpeername = 52,
  kSysSocketpair = 53,
  kSysSetsockopt = 54,
  kSysGetsockopt = 55,
  kSysClone = 56,
  kSysFork = 57,
  kSysVfork = 58,
  kSysExecve = 59,
  kSysExit = 60,
  kSysWait4 = 61,
  kSysKill = 62,
  kSysUname = 63,
  kSysSemget = 64,
  kSysSemop = 65,
  kSysSemctl = 66,
  kSysShmdt = 67,
  kSysMsgget = 68,
  kSysMsgsnd = 69,
  kSysMsgrcv = 70,
  kSysMsgctl = 71,
  kSysFcntl = 72,
  kSysFlock = 73,
  kSysFsync = 74,
  kSysFdatasync = 75,
  kSysTruncate = 76,
  kSysFtruncate = 77,
  kSysGetdents = 78,
  kSysGetcwd = 79,
  kSysChdir = 80,
  kSysFchdir = 81,
  kSysRename = 82,
  kSysMkdir = 83,
  kSysRmdir = 84,
  kSysCreat = 85,
  kSysLink = 86,
  kSysUnlink = 87,
  kSysSymlink = 88,
  kSysReadlink = 89,
  kSysChmod = 90,
  kSysFchmod = 91,
  kSysChown = 92,
  kSysFchown = 93,
  kSysLchown = 94,
  kSysUmask = 95,
  kSysGettimeofday = 96,
  kSysGetrlimit = 97,
  kSysGetrusage = 98,
  kSysSysinfo = 99,
  kSysTimes = 100,
  kSysPtrace = 101,
  kSysGetuid = 102,
  kSysSyslog = 103,
  kSysGetgid = 104,
  kSysSetuid = 105,
  kSysSetgid = 106,
  kSysGeteuid = 107,
  kSysGetegid = 108,
  kSysSetpgid = 109,
  kSysGetppid = 110,
  kSysGetpgrp = 111,
  kSysSetsid = 112,
  kSysSetreuid = 113,
  kSysSetregid = 114,
  kSysGetgroups = 115,
  kSysSetgroups = 116,
  kSysSetresuid = 117,
  kSysGetresuid = 118,
  kSysSetresgid = 119,
  kSysGetresgid = 120,
  kSysGetpgid = 121,
  kSysSetfsuid = 122,
  kSysSetfsgid = 123,
  kSysGetsid = 124,
  kSysCapget = 125,
  kSysCapset = 126,
  kSysRtSigpending = 127,
  kSysRtSigtimedwait = 128,
  kSysRtSigqueueinfo = 129,
  kSysRtSigsuspend = 130,
  kSysSigaltstack = 131,
  kSysUtime = 132,
  kSysMknod = 133,
  kSysUselib = 134,
  kSysPersonality = 135,
  kSysUstat = 136,
  kSysStatfs = 137,
  kSysFstatfs = 138,
  kSysSysfs = 139,
  kSysGetpriority = 140,
  kSysSetpriority = 141,
  kSysSchedSetparam = 142,
  kSysSchedGetparam = 143,
  kSysSchedSetscheduler = 144,
  kSysSchedGetscheduler = 145,
  kSysSchedGetPriorityMax = 146,
  kSysSchedGetPriorityMin = 147,
  kSysSchedRrGetInterval = 148,
  kSysMlock = 149,
  kSysMunlock = 150,
  kSysMlockall = 151,
  kSysMunlockall = 152,
  kSysVhangup = 153,
  kSysModifyLdt = 154,
  kSysPivotRoot = 155,
  kSysSysctl = 156,
  kSysPrctl = 157,
  kSysArchPrctl = 158,
  kSysAdjtimex = 159,
  kSysSetrlimit = 160,
  kSysChroot = 161,
  kSysSync = 162,
  kSysAcct = 163,
  kSysSettimeofday = 164,
  kSysMount = 165,
  kSysUmount2 = 166,
  kSysSwapon = 167,
  kSysSwapoff = 168,
  kSysReboot = 169,
  kSysSethostname = 170,
  kSysSetdomainname = 171,
  kSysIopl = 172,
  kSysIoperm = 173,
  kSysCreateModule = 174,
  kSysInitModule = 175,
  kSysDeleteModule = 176,
  kSysGetKernelSyms = 177,
  kSysQueryModule = 178,
  kSysQuotactl = 179,
  kSysNfsservctl = 180,
  kSysGetpmsg = 181,
  kSysPutpmsg = 182,
  kSysAfsSyscall = 183,
  kSysTuxcall = 184,
  kSysSecurity = 185,
  kSysGettid = 186,
  kSysReadahead = 187,
  kSysSetxattr = 188,
  kSysLsetxattr = 189,
  kSysFsetxattr = 190,
  kSysGetxattr = 191,
  kSysLgetxattr = 192,
  kSysFgetxattr = 193,
  kSysListxattr = 194,
  kSysLlistxattr = 195,
  kSysFlistxattr = 196,
  kSysRemovexattr = 197,
  kSysLremovexattr = 198,
  kSysFremovexattr = 199,
  kSysTkill = 200,
  kSysTime = 201,
  kSysFutex = 202,
  kSysSchedSetaffinity = 203,
  kSysSchedGetaffinity = 204,
  kSysSetThreadArea = 205,
  kSysIoSetup = 206,
  kSysIoDestroy = 207,
  kSysIoGetevents = 208,
  kSysIoSubmit = 209,
  kSysIoCancel = 210,
  kSysGetThreadArea = 211,
  kSysLookupDcookie = 212,
  kSysEpollCreate = 213,
  kSysEpollCtlOld = 214,
  kSysEpollWaitOld = 215,
  kSysRemapFilePages = 216,
  kSysGetdents64 = 217,
  kSysSetTidAddress = 218,
  kSysRestartSyscall = 219,
  kSysSemtimedop = 220,
  kSysFadvise64 = 221,
  kSysTimerCreate = 222,
  kSysTimerSettime = 223,
  kSysTimerGettime = 224,
  kSysTimerGetoverrun = 225,
  kSysTimerDelete = 226,
  kSysClockSettime = 227,
  kSysClockGettime = 228,
  kSysClockGetres = 229,
  kSysClockNanosleep = 230,
  kSysExitGroup = 231,
  kSysEpollWait = 232,
  kSysEpollCtl = 233,
  kSysTgkill = 234,
  kSysUtimes = 235,
  kSysVserver = 236,
  kSysMbind = 237,
  kSysSetMempolicy = 238,
  kSysGetMempolicy = 239,
  kSysMqOpen = 240,
  kSysMqUnlink = 241,
  kSysMqTimedsend = 242,
  kSysMqTimedreceive = 243,
  kSysMqNotify = 244,
  kSysMqGetsetattr = 245,
  kSysKexecLoad = 246,
  kSysWaitid = 247,
  kSysAddKey = 248,
  kSysRequestKey = 249,
  kSysKeyctl = 250,
  kSysIoprioSet = 251,
  kSysIoprioGet = 252,
  kSysInotifyInit = 253,
  kSysInotifyAddWatch = 254,
  kSysInotifyRmWatch = 255,
  kSysMigratePages = 256,
  kSysOpenat = 257,
  kSysMkdirat = 258,
  kSysMknodat = 259,
  kSysFchownat = 260,
  kSysFutimesat = 261,
  kSysNewfstatat = 262,
  kSysUnlinkat = 263,
  kSysRenameat = 264,
  kSysLinkat = 265,
  kSysSymlinkat = 266,
  kSysReadlinkat = 267,
  kSysFchmodat = 268,
  kSysFaccessat = 269,
  kSysPselect6 = 270,
  kSysPpoll = 271,
  kSysUnshare = 272,
  kSysSetRobustList = 273,
  kSysGetRobustList = 274,
  kSysSplice = 275,
  kSysTee = 276,
  kSysSyncFileRange = 277,
  kSysVmsplice = 278,
  kSysMovePages = 279,
  kSysUtimensat = 280,
  kSysEpollPwait = 281,
  kSysSignalfd = 282,
  kSysTimerfdCreate = 283,
  kSysEventfd = 284,
  kSysFallocate = 285,
  kSysTimerfdSettime = 286,
  kSysTimerfdGettime = 287,
  kSysAccept4 = 288,
  kSysSignalfd4 = 289,
  kSysEventfd2 = 290,
  kSysEpollCreate1 = 291,
  kSysDup3 = 292,
  kSysPipe2 = 293,
  kSysInotifyInit1 = 294,
  kSysPreadv = 295,
  kSysPwritev = 296,
  kSysRtTgsigqueueinfo = 297,
  kSysPerfEventOpen = 298,
  kSysRecvmmsg = 299,
  kSysFanotifyInit = 300,
  kSysFanotifyMark = 301,
  kSysPrlimit64 = 302,
  kSysNameToHandleAt = 303,
  kSysOpenByHandleAt = 304,
  kSysClockAdjtime = 305,
  kSysSyncfs = 306,
  kSysSendmmsg = 307,
  kSysSetns = 308,
  kSysGetcpu = 309,
  kSysProcessVmReadv = 310,
  kSysProcessVmWritev = 311,
  kSysKcmp = 312,
  kSysFinitModule = 313,
  kSysSchedSetattr = 314,
  kSysSchedGetattr = 315,
  kSysRenameat2 = 316,
  kSysSeccomp = 317,
  kSysGetrandom = 318,
  kSysMemfdCreate = 319,
  kSysKexecFileLoad = 320,
  kSysBpf = 321,
  kSysExecveat = 322,
  kSysUserfaultfd = 323,
  kSysMembarrier = 324,
  kSysMlock2 = 325,
  kSysCopyFileRange = 326,
  kSysPreadv2 = 327,
  kSysPwritev2 = 328,
  kSysPkeyMprotect = 329,
  kSysPkeyAlloc = 330,
  kSysPkeyFree = 331,
  kSysStatx = 332,
  kSysIoPgetevents = 333,
  kSysRseq = 334,
  kSysPidfdSendSignal = 424,
  kSysIoUringSetup = 425,
  kSysIoUringEnter = 426,
  kSysIoUringRegister = 427,
  kSysOpenTree = 428,
  kSysMoveMount = 429,
  kSysFsopen = 430,
  kSysFsconfig = 431,
  kSysFsmount = 432,
  kSysFspick = 433,
  kSysPidfdOpen = 434,
  kSysClone3 = 435,
  kSysCloseRange = 436,
  kSysOpenat2 = 437,
  kSysPidfdGetfd = 438,
  kSysFaccessat2 = 439,
  kSysProcessMadvise = 440,
  kSysEpollPwait2 = 441,
  kSysMountSetattr = 442,
  kSysQuotactlFd = 443,
  kSysLandlockCreateRuleset = 444,
  kSysLandlockAddRule = 445,
  kSysLandlockRestrictSelf = 446,
  kSysMemfdSecret = 447,
  kSysProcessMrelease = 448,
  kSysFutexWaitv = 449,
  kSysSetMempolicyHomeNode = 450,
  kSysCachestat = 451,
  kSysFadvise64_2 = 452,

  // Extended system calls for compatibility
  kSysArchSpecificSyscall = 500,
  kSysX32Syscall = 512,
  kSysX32Read = 512,
  kSysX32Write = 513,
  kSysX32Open = 514,
  kSysX32Close = 515,
  kSysX32Stat = 516,
  kSysX32Fstat = 517,
  kSysX32Lstat = 518,
  kSysX32Poll = 519,
  kSysX32Lseek = 520,
  kSysX32Mmap = 521,
  kSysX32Mprotect = 522,
  kSysX32Munmap = 523,
  kSysX32Brk = 524,
  kSysX32RtSigaction = 525,
  kSysX32RtSigprocmask = 526,
  kSysX32RtSigreturn = 527,
  kSysX32Ioctl = 528,
  kSysX32Pread64 = 529,
  kSysX32Pwrite64 = 530,
  kSysX32Readv = 531,
  kSysX32Writev = 532,
  kSysX32Access = 533,
  kSysX32Pipe = 534,
  kSysX32Select = 535,
  kSysX32SchedYield = 536,
  kSysX32Mremap = 537,
  kSysX32Msync = 538,
  kSysX32Mincore = 539,
  kSysX32Madvise = 540,
  kSysX32Shmget = 541,
  kSysX32Shmat = 542,
  kSysX32Shmctl = 543,
  kSysX32Dup = 544,
  kSysX32Dup2 = 545,
  kSysX32Pause = 546,
  kSysX32Nanosleep = 547,
  kSysX32Getitimer = 548,
  kSysX32Alarm = 549,
  kSysX32Setitimer = 550
};

// Mapping of syscall name as string to syscall number
static std::unordered_map<std::string, UnixSyscall> syscall_id_lookup_table = {
    {"read", kSysRead},
    {"write", kSysWrite},
    {"open", kSysOpen},
    {"close", kSysClose},
    {"stat", kSysStat},
    {"fstat", kSysFstat},
    {"lstat", kSysLstat},
    {"poll", kSysPoll},
    {"lseek", kSysLseek},
    {"mmap", kSysMmap},
    {"mprotect", kSysMprotect},
    {"munmap", kSysMunmap},
    {"brk", kSysBrk},
    {"rt_sigaction", kSysRtSigaction},
    {"rt_sigprocmask", kSysRtSigprocmask},
    {"rt_sigreturn", kSysRtSigreturn},
    {"ioctl", kSysIoctl},
    {"pread64", kSysPread64},
    {"pwrite64", kSysPwrite64},
    {"readv", kSysReadv},
    {"writev", kSysWritev},
    {"access", kSysAccess},
    {"pipe", kSysPipe},
    {"select", kSysSelect},
    {"sched_yield", kSysSchedYield},
    {"mremap", kSysMremap},
    {"msync", kSysMsync},
    {"mincore", kSysMincore},
    {"madvise", kSysMadvise},
    {"shmget", kSysShmget},
    {"shmat", kSysShmat},
    {"shmctl", kSysShmctl},
    {"dup", kSysDup},
    {"dup2", kSysDup2},
    {"pause", kSysPause},
    {"nanosleep", kSysNanosleep},
    {"getitimer", kSysGetitimer},
    {"alarm", kSysAlarm},
    {"setitimer", kSysSetitimer},
    {"getpid", kSysGetpid},
    {"sendfile", kSysSendfile},
    {"socket", kSysSocket},
    {"connect", kSysConnect},
    {"accept", kSysAccept},
    {"sendto", kSysSendto},
    {"recvfrom", kSysRecvfrom},
    {"sendmsg", kSysSendmsg},
    {"recvmsg", kSysRecvmsg},
    {"shutdown", kSysShutdown},
    {"bind", kSysBind},
    {"listen", kSysListen},
    {"getsockname", kSysGetsockname},
    {"getpeername", kSysGetpeername},
    {"socketpair", kSysSocketpair},
    {"setsockopt", kSysSetsockopt},
    {"getsockopt", kSysGetsockopt},
    {"clone", kSysClone},
    {"fork", kSysFork},
    {"vfork", kSysVfork},
    {"execve", kSysExecve},
    {"exit", kSysExit},
    {"wait4", kSysWait4},
    {"kill", kSysKill},
    {"uname", kSysUname},
    {"semget", kSysSemget},
    {"semop", kSysSemop},
    {"semctl", kSysSemctl},
    {"shmdt", kSysShmdt},
    {"msgget", kSysMsgget},
    {"msgsnd", kSysMsgsnd},
    {"msgrcv", kSysMsgrcv},
    {"msgctl", kSysMsgctl},
    {"fcntl", kSysFcntl},
    {"flock", kSysFlock},
    {"fsync", kSysFsync},
    {"fdatasync", kSysFdatasync},
    {"truncate", kSysTruncate},
    {"ftruncate", kSysFtruncate},
    {"getdents", kSysGetdents},
    {"getcwd", kSysGetcwd},
    {"chdir", kSysChdir},
    {"fchdir", kSysFchdir},
    {"rename", kSysRename},
    {"mkdir", kSysMkdir},
    {"rmdir", kSysRmdir},
    {"creat", kSysCreat},
    {"link", kSysLink},
    {"unlink", kSysUnlink},
    {"symlink", kSysSymlink},
    {"readlink", kSysReadlink},
    {"chmod", kSysChmod},
    {"fchmod", kSysFchmod},
    {"chown", kSysChown},
    {"fchown", kSysFchown},
    {"lchown", kSysLchown},
    {"umask", kSysUmask},
    {"gettimeofday", kSysGettimeofday},
    {"getrlimit", kSysGetrlimit},
    {"getrusage", kSysGetrusage},
    {"sysinfo", kSysSysinfo},
    {"times", kSysTimes},
    {"ptrace", kSysPtrace},
    {"getuid", kSysGetuid},
    {"syslog", kSysSyslog},
    {"getgid", kSysGetgid},
    {"setuid", kSysSetuid},
    {"setgid", kSysSetgid},
    {"geteuid", kSysGeteuid},
    {"getegid", kSysGetegid},
    {"setpgid", kSysSetpgid},
    {"getppid", kSysGetppid},
    {"getpgrp", kSysGetpgrp},
    {"setsid", kSysSetsid},
    {"setreuid", kSysSetreuid},
    {"setregid", kSysSetregid},
    {"getgroups", kSysGetgroups},
    {"setgroups", kSysSetgroups},
    {"setresuid", kSysSetresuid},
    {"getresuid", kSysGetresuid},
    {"setresgid", kSysSetresgid},
    {"getresgid", kSysGetresgid},
    {"getpgid", kSysGetpgid},
    {"setfsuid", kSysSetfsuid},
    {"setfsgid", kSysSetfsgid},
    {"getsid", kSysGetsid},
    {"capget", kSysCapget},
    {"capset", kSysCapset},
    {"rt_sigpending", kSysRtSigpending},
    {"rt_sigtimedwait", kSysRtSigtimedwait},
    {"rt_sigqueueinfo", kSysRtSigqueueinfo},
    {"rt_sigsuspend", kSysRtSigsuspend},
    {"sigaltstack", kSysSigaltstack},
    {"utime", kSysUtime},
    {"mknod", kSysMknod},
    {"uselib", kSysUselib},
    {"personality", kSysPersonality},
    {"ustat", kSysUstat},
    {"statfs", kSysStatfs},
    {"fstatfs", kSysFstatfs},
    {"sysfs", kSysSysfs},
    {"getpriority", kSysGetpriority},
    {"setpriority", kSysSetpriority},
    {"sched_setparam", kSysSchedSetparam},
    {"sched_getparam", kSysSchedGetparam},
    {"sched_setscheduler", kSysSchedSetscheduler},
    {"sched_getscheduler", kSysSchedGetscheduler},
    {"sched_get_priority_max", kSysSchedGetPriorityMax},
    {"sched_get_priority_min", kSysSchedGetPriorityMin},
    {"sched_rr_get_interval", kSysSchedRrGetInterval},
    {"mlock", kSysMlock},
    {"munlock", kSysMunlock},
    {"mlockall", kSysMlockall},
    {"munlockall", kSysMunlockall},
    {"vhangup", kSysVhangup},
    {"modify_ldt", kSysModifyLdt},
    {"pivot_root", kSysPivotRoot},
    {"sysctl", kSysSysctl},
    {"prctl", kSysPrctl},
    {"arch_prctl", kSysArchPrctl},
    {"adjtimex", kSysAdjtimex},
    {"setrlimit", kSysSetrlimit},
    {"chroot", kSysChroot},
    {"sync", kSysSync},
    {"acct", kSysAcct},
    {"settimeofday", kSysSettimeofday},
    {"mount", kSysMount},
    {"umount2", kSysUmount2},
    {"swapon", kSysSwapon},
    {"swapoff", kSysSwapoff},
    {"reboot", kSysReboot},
    {"sethostname", kSysSethostname},
    {"setdomainname", kSysSetdomainname},
    {"iopl", kSysIopl},
    {"ioperm", kSysIoperm},
    {"create_module", kSysCreateModule},
    {"init_module", kSysInitModule},
    {"delete_module", kSysDeleteModule},
    {"get_kernel_syms", kSysGetKernelSyms},
    {"query_module", kSysQueryModule},
    {"quotactl", kSysQuotactl},
    {"nfsservctl", kSysNfsservctl},
    {"getpmsg", kSysGetpmsg},
    {"putpmsg", kSysPutpmsg},
    {"afs_syscall", kSysAfsSyscall},
    {"tuxcall", kSysTuxcall},
    {"security", kSysSecurity},
    {"gettid", kSysGettid},
    {"readahead", kSysReadahead},
    {"setxattr", kSysSetxattr},
    {"lsetxattr", kSysLsetxattr},
    {"fsetxattr", kSysFsetxattr},
    {"getxattr", kSysGetxattr},
    {"lgetxattr", kSysLgetxattr},
    {"fgetxattr", kSysFgetxattr},
    {"listxattr", kSysListxattr},
    {"llistxattr", kSysLlistxattr},
    {"flistxattr", kSysFlistxattr},
    {"removexattr", kSysRemovexattr},
    {"lremovexattr", kSysLremovexattr},
    {"fremovexattr", kSysFremovexattr},
    {"tkill", kSysTkill},
    {"time", kSysTime},
    {"futex", kSysFutex},
    {"sched_setaffinity", kSysSchedSetaffinity},
    {"sched_getaffinity", kSysSchedGetaffinity},
    {"set_thread_area", kSysSetThreadArea},
    {"io_setup", kSysIoSetup},
    {"io_destroy", kSysIoDestroy},
    {"io_getevents", kSysIoGetevents},
    {"io_submit", kSysIoSubmit},
    {"io_cancel", kSysIoCancel},
    {"get_thread_area", kSysGetThreadArea},
    {"lookup_dcookie", kSysLookupDcookie},
    {"epoll_create", kSysEpollCreate},
    {"epoll_ctl_old", kSysEpollCtlOld},
    {"epoll_wait_old", kSysEpollWaitOld},
    {"remap_file_pages", kSysRemapFilePages},
    {"getdents64", kSysGetdents64},
    {"set_tid_address", kSysSetTidAddress},
    {"restart_syscall", kSysRestartSyscall},
    {"semtimedop", kSysSemtimedop},
    {"fadvise64", kSysFadvise64},
    {"timer_create", kSysTimerCreate},
    {"timer_settime", kSysTimerSettime},
    {"timer_gettime", kSysTimerGettime},
    {"timer_getoverrun", kSysTimerGetoverrun},
    {"timer_delete", kSysTimerDelete},
    {"clock_settime", kSysClockSettime},
    {"clock_gettime", kSysClockGettime},
    {"clock_getres", kSysClockGetres},
    {"clock_nanosleep", kSysClockNanosleep},
    {"exit_group", kSysExitGroup},
    {"epoll_wait", kSysEpollWait},
    {"epoll_ctl", kSysEpollCtl},
    {"tgkill", kSysTgkill},
    {"utimes", kSysUtimes},
    {"vserver", kSysVserver},
    {"mbind", kSysMbind},
    {"set_mempolicy", kSysSetMempolicy},
    {"get_mempolicy", kSysGetMempolicy},
    {"mq_open", kSysMqOpen},
    {"mq_unlink", kSysMqUnlink},
    {"mq_timedsend", kSysMqTimedsend},
    {"mq_timedreceive", kSysMqTimedreceive},
    {"mq_notify", kSysMqNotify},
    {"mq_getsetattr", kSysMqGetsetattr},
    {"kexec_load", kSysKexecLoad},
    {"waitid", kSysWaitid},
    {"add_key", kSysAddKey},
    {"request_key", kSysRequestKey},
    {"keyctl", kSysKeyctl},
    {"ioprio_set", kSysIoprioSet},
    {"ioprio_get", kSysIoprioGet},
    {"inotify_init", kSysInotifyInit},
    {"inotify_add_watch", kSysInotifyAddWatch},
    {"inotify_rm_watch", kSysInotifyRmWatch},
    {"migrate_pages", kSysMigratePages},
    {"openat", kSysOpenat},
    {"mkdirat", kSysMkdirat},
    {"mknodat", kSysMknodat},
    {"fchownat", kSysFchownat},
    {"futimesat", kSysFutimesat},
    {"newfstatat", kSysNewfstatat},
    {"unlinkat", kSysUnlinkat},
    {"renameat", kSysRenameat},
    {"linkat", kSysLinkat},
    {"symlinkat", kSysSymlinkat},
    {"readlinkat", kSysReadlinkat},
    {"fchmodat", kSysFchmodat},
    {"faccessat", kSysFaccessat},
    {"pselect6", kSysPselect6},
    {"ppoll", kSysPpoll},
    {"unshare", kSysUnshare},
    {"set_robust_list", kSysSetRobustList},
    {"get_robust_list", kSysGetRobustList},
    {"splice", kSysSplice},
    {"tee", kSysTee},
    {"sync_file_range", kSysSyncFileRange},
    {"vmsplice", kSysVmsplice},
    {"move_pages", kSysMovePages},
    {"utimensat", kSysUtimensat},
    {"epoll_pwait", kSysEpollPwait},
    {"signalfd", kSysSignalfd},
    {"timerfd_create", kSysTimerfdCreate},
    {"eventfd", kSysEventfd},
    {"fallocate", kSysFallocate},
    {"timerfd_settime", kSysTimerfdSettime},
    {"timerfd_gettime", kSysTimerfdGettime},
    {"accept4", kSysAccept4},
    {"signalfd4", kSysSignalfd4},
    {"eventfd2", kSysEventfd2},
    {"epoll_create1", kSysEpollCreate1},
    {"dup3", kSysDup3},
    {"pipe2", kSysPipe2},
    {"inotify_init1", kSysInotifyInit1},
    {"preadv", kSysPreadv},
    {"pwritev", kSysPwritev},
    {"rt_tgsigqueueinfo", kSysRtTgsigqueueinfo},
    {"perf_event_open", kSysPerfEventOpen},
    {"recvmmsg", kSysRecvmmsg},
    {"fanotify_init", kSysFanotifyInit},
    {"fanotify_mark", kSysFanotifyMark},
    {"prlimit64", kSysPrlimit64},
    {"name_to_handle_at", kSysNameToHandleAt},
    {"open_by_handle_at", kSysOpenByHandleAt},
    {"clock_adjtime", kSysClockAdjtime},
    {"syncfs", kSysSyncfs},
    {"sendmmsg", kSysSendmmsg},
    {"setns", kSysSetns},
    {"getcpu", kSysGetcpu},
    {"process_vm_readv", kSysProcessVmReadv},
    {"process_vm_writev", kSysProcessVmWritev},
    {"kcmp", kSysKcmp},
    {"finit_module", kSysFinitModule},
    {"sched_setattr", kSysSchedSetattr},
    {"sched_getattr", kSysSchedGetattr},
    {"renameat2", kSysRenameat2},
    {"seccomp", kSysSeccomp},
    {"getrandom", kSysGetrandom},
    {"memfd_create", kSysMemfdCreate},
    {"kexec_file_load", kSysKexecFileLoad},
    {"bpf", kSysBpf},
    {"execveat", kSysExecveat},
    {"userfaultfd", kSysUserfaultfd},
    {"membarrier", kSysMembarrier},
    {"mlock2", kSysMlock2},
    {"copy_file_range", kSysCopyFileRange},
    {"preadv2", kSysPreadv2},
    {"pwritev2", kSysPwritev2},
    {"pkey_mprotect", kSysPkeyMprotect},
    {"pkey_alloc", kSysPkeyAlloc},
    {"pkey_free", kSysPkeyFree},
    {"statx", kSysStatx},
    {"io_pgetevents", kSysIoPgetevents},
    {"rseq", kSysRseq},
    {"pidfd_send_signal", kSysPidfdSendSignal},
    {"io_uring_setup", kSysIoUringSetup},
    {"io_uring_enter", kSysIoUringEnter},
    {"io_uring_register", kSysIoUringRegister},
    {"open_tree", kSysOpenTree},
    {"move_mount", kSysMoveMount},
    {"fsopen", kSysFsopen},
    {"fsconfig", kSysFsconfig},
    {"fsmount", kSysFsmount},
    {"fspick", kSysFspick},
    {"pidfd_open", kSysPidfdOpen},
    {"clone3", kSysClone3},
    {"close_range", kSysCloseRange},
    {"openat2", kSysOpenat2},
    {"pidfd_getfd", kSysPidfdGetfd},
    {"faccessat2", kSysFaccessat2},
    {"process_madvise", kSysProcessMadvise},
    {"epoll_pwait2", kSysEpollPwait2},
    {"mount_setattr", kSysMountSetattr},
    {"quotactl_fd", kSysQuotactlFd},
    {"landlock_create_ruleset", kSysLandlockCreateRuleset},
    {"landlock_add_rule", kSysLandlockAddRule},
    {"landlock_restrict_self", kSysLandlockRestrictSelf},
    {"memfd_secret", kSysMemfdSecret},
    {"process_mrelease", kSysProcessMrelease},
    {"futex_waitv", kSysFutexWaitv},
    {"set_mempolicy_home_node", kSysSetMempolicyHomeNode},
    {"cachestat", kSysCachestat},
    {"fadvise64_2", kSysFadvise64_2}
};

// Mapping of syscall number to syscall name
static std::unordered_map<uint16_t, std::string> syscall_name_lookup_table = {
    {0, "read"},
    {1, "write"},
    {2, "open"},
    {3, "close"},
    {4, "stat"},
    {5, "fstat"},
    {6, "lstat"},
    {7, "poll"},
    {8, "lseek"},
    {9, "mmap"},
    {10, "mprotect"},
    {11, "munmap"},
    {12, "brk"},
    {13, "rt_sigaction"},
    {14, "rt_sigprocmask"},
    {15, "rt_sigreturn"},
    {16, "ioctl"},
    {17, "pread64"},
    {18, "pwrite64"},
    {19, "readv"},
    {20, "writev"},
    {21, "access"},
    {22, "pipe"},
    {23, "select"},
    {24, "sched_yield"},
    {25, "mremap"},
    {26, "msync"},
    {27, "mincore"},
    {28, "madvise"},
    {29, "shmget"},
    {30, "shmat"},
    {31, "shmctl"},
    {32, "dup"},
    {33, "dup2"},
    {34, "pause"},
    {35, "nanosleep"},
    {36, "getitimer"},
    {37, "alarm"},
    {38, "setitimer"},
    {39, "getpid"},
    {40, "sendfile"},
    {41, "socket"},
    {42, "connect"},
    {43, "accept"},
    {44, "sendto"},
    {45, "recvfrom"},
    {46, "sendmsg"},
    {47, "recvmsg"},
    {48, "shutdown"},
    {49, "bind"},
    {50, "listen"},
    {51, "getsockname"},
    {52, "getpeername"},
    {53, "socketpair"},
    {54, "setsockopt"},
    {55, "getsockopt"},
    {56, "clone"},
    {57, "fork"},
    {58, "vfork"},
    {59, "execve"},
    {60, "exit"},
    {61, "wait4"},
    {62, "kill"},
    {63, "uname"},
    {64, "semget"},
    {65, "semop"},
    {66, "semctl"},
    {67, "shmdt"},
    {68, "msgget"},
    {69, "msgsnd"},
    {70, "msgrcv"},
    {71, "msgctl"},
    {72, "fcntl"},
    {73, "flock"},
    {74, "fsync"},
    {75, "fdatasync"},
    {76, "truncate"},
    {77, "ftruncate"},
    {78, "getdents"},
    {79, "getcwd"},
    {80, "chdir"},
    {81, "fchdir"},
    {82, "rename"},
    {83, "mkdir"},
    {84, "rmdir"},
    {85, "creat"},
    {86, "link"},
    {87, "unlink"},
    {88, "symlink"},
    {89, "readlink"},
    {90, "chmod"},
    {91, "fchmod"},
    {92, "chown"},
    {93, "fchown"},
    {94, "lchown"},
    {95, "umask"},
    {96, "gettimeofday"},
    {97, "getrlimit"},
    {98, "getrusage"},
    {99, "sysinfo"},
    {100, "times"},
    {101, "ptrace"},
    {102, "getuid"},
    {103, "syslog"},
    {104, "getgid"},
    {105, "setuid"},
    {106, "setgid"},
    {107, "geteuid"},
    {108, "getegid"},
    {109, "setpgid"},
    {110, "getppid"},
    {111, "getpgrp"},
    {112, "setsid"},
    {113, "setreuid"},
    {114, "setregid"},
    {115, "getgroups"},
    {116, "setgroups"},
    {117, "setresuid"},
    {118, "getresuid"},
    {119, "setresgid"},
    {120, "getresgid"},
    {121, "getpgid"},
    {122, "setfsuid"},
    {123, "setfsgid"},
    {124, "getsid"},
    {125, "capget"},
    {126, "capset"},
    {127, "rt_sigpending"},
    {128, "rt_sigtimedwait"},
    {129, "rt_sigqueueinfo"},
    {130, "rt_sigsuspend"},
    {131, "sigaltstack"},
    {132, "utime"},
    {133, "mknod"},
    {134, "uselib"},
    {135, "personality"},
    {136, "ustat"},
    {137, "statfs"},
    {138, "fstatfs"},
    {139, "sysfs"},
    {140, "getpriority"},
    {141, "setpriority"},
    {142, "sched_setparam"},
    {143, "sched_getparam"},
    {144, "sched_setscheduler"},
    {145, "sched_getscheduler"},
    {146, "sched_get_priority_max"},
    {147, "sched_get_priority_min"},
    {148, "sched_rr_get_interval"},
    {149, "mlock"},
    {150, "munlock"},
    {151, "mlockall"},
    {152, "munlockall"},
    {153, "vhangup"},
    {154, "modify_ldt"},
    {155, "pivot_root"},
    {156, "sysctl"},
    {157, "prctl"},
    {158, "arch_prctl"},
    {159, "adjtimex"},
    {160, "setrlimit"},
    {161, "chroot"},
    {162, "sync"},
    {163, "acct"},
    {164, "settimeofday"},
    {165, "mount"},
    {166, "umount2"},
    {167, "swapon"},
    {168, "swapoff"},
    {169, "reboot"},
    {170, "sethostname"},
    {171, "setdomainname"},
    {172, "iopl"},
    {173, "ioperm"},
    {174, "create_module"},
    {175, "init_module"},
    {176, "delete_module"},
    {177, "get_kernel_syms"},
    {178, "query_module"},
    {179, "quotactl"},
    {180, "nfsservctl"},
    {181, "getpmsg"},
    {182, "putpmsg"},
    {183, "afs_syscall"},
    {184, "tuxcall"},
    {205, "set_thread_area"},
    {206, "io_setup"},
    {207, "io_destroy"},
    {208, "io_getevents"},
    {209, "io_submit"},
    {210, "io_cancel"},
    {211, "get_thread_area"},
    {212, "lookup_dcookie"},
    {213, "epoll_create"},
    {214, "epoll_ctl_old"},
    {215, "epoll_wait_old"},
    {216, "remap_file_pages"},
    {217, "getdents64"},
    {218, "set_tid_address"},
    {219, "restart_syscall"},
    {220, "semtimedop"},
    {221, "fadvise64"},
    {222, "timer_create"},
    {223, "timer_settime"},
    {224, "timer_gettime"},
    {225, "timer_getoverrun"},
    {226, "timer_delete"},
    {227, "clock_settime"},
    {228, "clock_gettime"},
    {229, "clock_getres"},
    {230, "clock_nanosleep"},
    {231, "exit_group"},
    {232, "epoll_wait"},
    {233, "epoll_ctl"},
    {234, "tgkill"},
    {235, "utimes"},
    {236, "vserver"},
    {237, "mbind"},
    {238, "set_mempolicy"},
    {239, "get_mempolicy"},
    {240, "mq_open"},
    {241, "mq_unlink"},
    {242, "mq_timedsend"},
    {243, "mq_timedreceive"},
    {244, "mq_notify"},
    {245, "mq_getsetattr"},
    {246, "kexec_load"},
    {247, "waitid"},
    {248, "add_key"},
    {249, "request_key"},
    {250, "keyctl"},
    {251, "ioprio_set"},
    {252, "ioprio_get"},
    {253, "inotify_init"},
    {254, "inotify_add_watch"},
    {255, "inotify_rm_watch"},
    {256, "migrate_pages"},
    {257, "openat"},
    {258, "mkdirat"},
    {259, "mknodat"},
    {260, "fchownat"},
    {261, "futimesat"},
    {262, "newfstatat"},
    {263, "unlinkat"},
    {264, "renameat"},
    {265, "linkat"},
    {266, "symlinkat"},
    {267, "readlinkat"},
    {268, "fchmodat"},
    {269, "faccessat"},
    {270, "pselect6"},
    {271, "ppoll"},
    {272, "unshare"},
    {273, "set_robust_list"},
    {274, "get_robust_list"},
    {275, "splice"},
    {276, "tee"},
    {277, "sync_file_range"},
    {278, "vmsplice"},
    {279, "move_pages"},
    {280, "utimensat"},
    {281, "epoll_pwait"},
    {282, "signalfd"},
    {283, "timerfd_create"},
    {284, "eventfd"},
    {285, "fallocate"},
    {286, "timerfd_settime"},
    {287, "timerfd_gettime"},
    {288, "accept4"},
    {289, "signalfd4"},
    {290, "eventfd2"},
    {291, "epoll_create1"},
    {292, "dup3"},
    {293, "pipe2"},
    {294, "inotify_init1"},
    {295, "preadv"},
    {296, "pwritev"},
    {297, "rt_tgsigqueueinfo"},
    {298, "perf_event_open"},
    {299, "recvmmsg"},
    {300, "fanotify_init"},
    {301, "fanotify_mark"},
    {302, "prlimit64"},
    {303, "name_to_handle_at"},
    {304, "open_by_handle_at"},
    {305, "clock_adjtime"},
    {306, "syncfs"},
    {307, "sendmmsg"},
    {308, "setns"},
    {309, "getcpu"},
    {310, "process_vm_readv"},
    {311, "process_vm_writev"},
    {312, "kcmp"},
    {313, "finit_module"},
    {314, "sched_setattr"},
    {315, "sched_getattr"},
    {316, "renameat2"},
    {317, "seccomp"},
    {318, "getrandom"},
    {319, "memfd_create"},
    {320, "kexec_file_load"},
    {321, "bpf"},
    {322, "execveat"},
    {323, "userfaultfd"},
    {324, "membarrier"},
    {325, "mlock2"},
    {326, "copy_file_range"},
    {327, "preadv2"},
    {328, "pwritev2"},
    {329, "pkey_mprotect"},
    {330, "pkey_alloc"},
    {331, "pkey_free"},
    {332, "statx"},
    {333, "io_pgetevents"},
    {334, "rseq"},
    {424, "pidfd_send_signal"},
    {425, "io_uring_setup"},
    {426, "io_uring_enter"},
    {427, "io_uring_register"},
    {428, "open_tree"},
    {429, "move_mount"},
    {430, "fsopen"},
    {431, "fsconfig"},
    {432, "fsmount"},
    {433, "fspick"},
    {434, "pidfd_open"},
    {435, "clone3"},
    {436, "close_range"},
    {437, "openat2"},
    {438, "pidfd_getfd"},
    {439, "faccessat2"},
    {440, "process_madvise"},
    {441, "epoll_pwait2"},
    {442, "mount_setattr"},
    {443, "quotactl_fd"},
    {444, "landlock_create_ruleset"},
    {445, "landlock_add_rule"},
    {446, "landlock_restrict_self"},
    {447, "memfd_secret"},
    {448, "process_mrelease"},
    {449, "futex_waitv"},
    {450, "set_mempolicy_home_node"},
    {451, "cachestat"},
    {452, "fadvise64_2"}
};

#endif  // SYSCALLID_H
